[workspace]
members = [
  "./crates/base",
  "./crates/cli",
  "./crates/sb_workers",
  "./crates/sb_env",
  "./crates/sb_core",
  "./crates/sb_os",
  "./crates/cpu_timer",
  "./crates/event_worker",
  "./crates/npm",
  "./crates/sb_graph",
  "./crates/sb_module_loader",
  "./crates/sb_fs",
  "./crates/sb_ai"
]
resolver = "2"

[workspace.dependencies]
url = { version = "2.3.1" }
eszip = "0.64.2"
log = "0.4.20"
anyhow = { version = "1.0.57" }
libc = { version = "0.2.144" }
deno_ast = { version = "0.34.1", features = ["transpiling"] }
deno_broadcast_channel = { version = "0.136.0" }
deno_core = { version = "0.270.0" }
deno_console = { version = "0.142.0" }
deno_crypto =  { version = "0.156.0" }
deno_fetch = { version = "0.166.0" }
deno_fs = { version = "0.52.0", features = ["sync_fs"] }
deno_config = "=0.14.1"
deno_io = "0.52.0"
deno_webgpu = "0.109.0"
deno_canvas = "0.11.0"
deno_graph = "=0.69.9"
deno_http =  { version = "0.139.0" }
deno_media_type = { version = "0.1.2", features = ["module_specifier"] }
deno_net = { version = "0.134.0" }
deno_npm = "0.17.0"
deno_url = { version = "0.142.0" }
deno_semver = "0.5.4"
deno_tls = { version = "0.129.0"}
deno_webidl = { version = "0.142.0" }
deno_web = { version = "0.173.0" }
deno_websocket = { version = "0.147.0" }
deno_webstorage = { version = "0.137.0" }
enum-as-inner = "0.6.0"
serde = { version = "1.0.149", features = ["derive"] }
hyper = "0.14.26"
tokio = { version = "1.35", features = ["full"] }
bytes = { version = "1.4.0" }
once_cell = "1.17.1"
thiserror = "1.0.40"
deno_lockfile = "0.19.0"
async-trait = "0.1.73"
indexmap = { version = "2.0.0", features = ["serde"] }
flate2 = "=1.0.26"
tar = "=0.4.40"
regex = "^1.7.0"
fs3 = "0.5.0"
tokio-util = "0.7.4"
uuid = { version = "1.3.0", features = ["v4"] }
rsa = { version = "0.9.3", default-features = false, features = ["std", "pem", "hazmat"] } # hazmat needed for PrehashSigner in ext/node
monch = "=0.5.0"
reqwest = { version = "0.11.20", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli", "socks", "json"] }
ring = "^0.17.0"
urlencoding = { version = "2.1.2" }
import_map = { version = "=0.18.0", features = ["ext"] }
base64 = "0.21.4"
futures = { version = "0.3.28" }
futures-util = { version = "0.3.28" }
ctor = { version = "0.2.6" }
fastwebsockets = { version = "0.4.4", features = ["upgrade"] }
percent-encoding = "2.3.0"
scopeguard = { version = "1.2.0" }
glob = "0.3.1"

# DEBUG
#[patch.crates-io]
#deno_core = { path = "/your/path/to/deno_core/core" }

[profile.release]
lto = true
