[package]
name = "sb_workers"
version = "0.1.0"
authors = ["Supabase <team@supabase.com>"]
edition = "2021"
resolver = "2"
description = "We'll take care of this later"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
uuid.workspace = true
deno_core.workspace = true
deno_web.workspace = true
tokio.workspace = true
deno_http.workspace = true
hyper.workspace = true
sb_eszip = { version = "0.1.0", path = "../sb_eszip" }
serde.workspace = true
bytes.workspace = true
log.workspace = true
sb_worker_context = { version = "0.1.0", path = "../sb_worker_context" }
event_worker ={ version = "0.1.0", path = "../event_worker" }
